### ISSUE TITLE
Retrieving a row containing datetime fields == null gives ConversionException

### ISSUE THREAD

**Issue by KarlLevik** [DiamondLightSource/gda-ispyb-api#66]
(The below test is currently on the SCI-8216 branch only.)

If I remove the `setStarttime` and `setEndtime` lines in the `testRetrieveDataCollectionGroup` test, I get an error like below. However, it should be possible to retrieve rows where a datetime field is null, so this is a bug that needs fixing.

> [ERROR] testRetrieveDataCollectionGroup(uk.ac.diamond.ispyb.test.DataCollectionIntegrationTest)  Time elapsed: 0.037 s  <<< ERROR!
> org.apache.commons.beanutils.ConversionException: No value specified for 'java.sql.Timestamp'
> 	at uk.ac.diamond.ispyb.test.DataCollectionIntegrationTest.lambda$testRetrieveDataCollectionGroup$9(DataCollectionIntegrationTest.java:155)
> 	at uk.ac.diamond.ispyb.test.DataCollectionIntegrationTest.testRetrieveDataCollectionGroup(DataCollectionIntegrationTest.java:155)
>

**Comment by KarlLevik** [comment]
Fixed in #70
